export const MSG = {
  authNeeded: '🔐 Autenticação necessária. Abri uma aba no seu browser pra login corporativo. Assim que finalizar, peça de novo o que você queria.',
  authCompleted: '🔐 Autenticação concluída com sucesso. Por favor, faça sua pergunta novamente.',
  authAborted: '🔐 Login não foi concluído. Quando estiver pronto, peça de novo que eu tento outra vez.',
  authWrongTenant: '⚠️ Você não está no tenant corporativo Azzas. Se isso é um engano, contate ai.labs@somagrupo.com.br.',
  authSessionExpired: '🔐 Sua sessão expirou. Abri uma aba pra você logar de novo.',
  authSessionInvalid: '🔐 Sua sessão foi invalidada. Abri uma aba pra você logar de novo.',
  authLoopbackPortsBusy: '⚠️ Não consegui abrir uma porta local pro login. Feche outras instâncias de MCP e tente de novo.',
  authCorruptCredentials: '🔐 Suas credenciais estavam corrompidas. Apaguei e abri uma aba de login.',
  networkManifestFail: '⚠️ Não consegui buscar a lista de ferramentas do Azzas. Verifique sua conexão e reinicie o Claude Desktop.',
  agentUnavailable: (name: string) => `⚠️ O agente \`${name}\` está indisponível no momento. Tente novamente em alguns minutos.`,
  agentForbidden: (name: string) => `⚠️ Seu e-mail não tem acesso ao agente \`${name}\`. Se isso é um engano, contate ai.labs@somagrupo.com.br.`,
  unknownTool: (tool: string) => `⚠️ Ferramenta \`${tool}\` não reconhecida. A lista de agentes pode ter mudado — reinicie o Claude Desktop.`,
  malformedAgentResponse: (name: string, onboardingUrl?: string) => `⚠️ O agente \`${name}\` devolveu uma resposta inesperada. Primeira tentativa: baixe a versão mais nova do Azzas MCP${onboardingUrl ? ` em ${onboardingUrl}` : ''} e reinstale. Se persistir, contate ai.labs@somagrupo.com.br.`,
  versionStale: (current: string, url: string) => `⚠️ Sua versão do Azzas MCP (v${current}) não é mais suportada. Baixe a versão mais nova em ${url}.`,
};
